// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvh7tWLOJRWsx23WUEULBvlFBUFhMxY7w',
    appId: '1:541591020969:web:473709f826b641572190b8',
    messagingSenderId: '541591020969',
    projectId: 'ungansatt123',
    authDomain: 'ungansatt123.firebaseapp.com',
    storageBucket: 'ungansatt123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHfsdczq-kB355xr7G56WrAzChJodaTe8',
    appId: '1:541591020969:android:936caebf02a36e922190b8',
    messagingSenderId: '541591020969',
    projectId: 'ungansatt123',
    storageBucket: 'ungansatt123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxBXPswg-rpAfksGTKLso07F7XL9YuC1A',
    appId: '1:541591020969:ios:9281da2bafdf864d2190b8',
    messagingSenderId: '541591020969',
    projectId: 'ungansatt123',
    storageBucket: 'ungansatt123.appspot.com',
    iosClientId: '541591020969-cjson7b7guo79u4ukatic4o9km1b15uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.webdesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxBXPswg-rpAfksGTKLso07F7XL9YuC1A',
    appId: '1:541591020969:ios:6c8c3ca5e3d2195e2190b8',
    messagingSenderId: '541591020969',
    projectId: 'ungansatt123',
    storageBucket: 'ungansatt123.appspot.com',
    iosClientId: '541591020969-clhusgarjpvq55i4frcf5477q8l4mqpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.webdesign.RunnerTests',
  );
}
